spring:
  application:
    name: carros API
  datasource:
    url: jdbc:h2:mem:carros
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console